name: tmp2
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=24.2
  - python=3.10.12
  - setuptools=72.1.0
  - wheel=0.44.0
  - pip:
      - absl-py==1.4.0
      - altair==5.1.2
      - anyio==4.0.0
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - asteval==0.9.31
      - asttokens==2.4.0
      - astunparse==1.6.3
      - async-lru==2.0.4
      - attrs==23.1.0
      - babel==2.12.1
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - bleach==6.0.0
      - blinker==1.6.3
      - blosc2==2.0.0
      - brotlipy==0.7.0
      - cachetools==5.3.1
      - certifi==2023.7.22
      - cffi==1.16.0
      - charset-normalizer==3.3.1
      - click==8.1.7
      - cloudpickle==3.0.0
      - comm==0.1.4
      - contourpy==1.1.0
      - cycler==0.11.0
      - cython==3.0.2
      - dask==2023.10.0
      - debugpy==1.7.0
      - decorator==4.4.2
      - defusedxml==0.7.1
      - docker-pycreds==0.4.0
      - dphtools==0.0.5
      - exceptiongroup==1.2.2
      - executing==1.2.0
      - fastjsonschema==2.18.0
      - flatbuffers==23.5.26
      - fonttools==4.42.1
      - fqdn==1.5.1
      - fsspec==2023.10.0
      - funcsigs==1.0.2
      - future==0.18.3
      - gast==0.4.0
      - gitdb==4.0.11
      - gitpython==3.1.40
      - google-auth==2.22.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - greenlet==3.0.1
      - grpcio==1.58.0
      - gviz-api==1.10.0
      - h11==0.14.0
      - h5py==3.9.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - idna==3.4
      - imagecodecs==2024.6.1
      - imagecodes==0.0.1
      - imageio==2.31.3
      - imageio-ffmpeg==0.4.9
      - importlib-metadata==6.8.0
      - ipykernel==6.26.0
      - ipython==8.15.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.0
      - isoduration==20.11.0
      - jedi==0.19.0
      - jinja2==3.1.2
      - joblib==1.3.2
      - json5==0.9.14
      - jsonpointer==2.1
      - jsonschema==4.19.0
      - jsonschema-specifications==2023.7.1
      - jupyter-client==8.3.1
      - jupyter-console==6.6.3
      - jupyter-core==5.3.1
      - jupyter-events==0.7.0
      - jupyter-lsp==2.2.0
      - jupyter-server==2.7.3
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.2.3
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.27.2
      - jupyterlab-widgets==3.0.8
      - keras==2.14.0
      - kiwisolver==1.4.5
      - libclang==16.0.6
      - llvmlite==0.41.1
      - lmfit==1.2.2
      - locket==1.0.0
      - markdown==3.4.4
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - mat73==0.62
      - matplotlib==3.7.3
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - mistune==3.0.1
      - ml-dtypes==0.2.0
      - moviepy==1.0.3
      - mpmath==1.3.0
      - msgpack==1.0.5
      - natsort==8.4.0
      - nbclient==0.8.0
      - nbconvert==7.8.0
      - nbformat==5.9.2
      - nd2==0.7.2
      - nd2reader==3.3.0
      - nest-asyncio==1.5.7
      - networkx==3.1
      - notebook==7.2.1
      - notebook-shim==0.2.3
      - numba==0.58.0
      - numexpr==2.8.5
      - numpy==1.24.3
      - oauthlib==3.2.2
      - opencv-python==4.8.0.76
      - opt-einsum==3.3.0
      - overrides==7.4.0
      - p2j==1.3.2
      - packaging==23.2
      - pandas==2.1.1
      - pandocfilters==1.5.0
      - parso==0.8.3
      - partd==1.4.1
      - patsy==0.5.3
      - pexpect==4.8.0
      - picassosr==0.7.0
      - pickleshare==0.7.5
      - pillow==9.5.0
      - pims==0.6.1
      - platformdirs==3.10.0
      - plotly==5.18.0
      - plotly-express==0.4.1
      - proglog==0.1.10
      - prometheus-client==0.17.1
      - prompt-toolkit==3.0.39
      - protobuf==4.24.3
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - pyaml==24.4.0
      - pyarrow==13.0.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pydeck==0.8.1b0
      - pydot==2.0.0
      - pygments==2.16.1
      - pylance==0.13.0
      - pyotf==0.0.3
      - pyparsing==3.0.9
      - pyqt5==5.15.10
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.13.0
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pytz==2023.3.post1
      - pywavelets==1.4.1
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - qtconsole==5.4.4
      - qtpy==2.4.0
      - referencing==0.30.2
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - resource-backed-dask-array==0.1.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.6.0
      - rpds-py==0.10.2
      - rsa==4.9
      - scikit-image==0.19.3
      - scikit-learn==1.3.1
      - scipy==1.11.2
      - seaborn==0.13.0
      - send2trash==1.8.2
      - sentry-sdk==1.43.0
      - setproctitle==1.3.3
      - six==1.16.0
      - slicerator==1.1.0
      - smmap==5.0.1
      - sniffio==1.3.0
      - soupsieve==2.5
      - sqlalchemy==2.0.21
      - stack-data==0.6.2
      - statsmodels==0.14.0
      - streamlit==1.27.0
      - sympy==1.12
      - tables==3.8.0
      - tenacity==8.2.3
      - tensorboard==2.14.1
      - tensorboard-data-server==0.7.1
      - tensorboard-plugin-profile==2.15.1
      - tensorflow==2.14.0
      - tensorflow-addons==0.21.0
      - tensorflow-estimator==2.14.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - termcolor==2.3.0
      - terminado==0.17.1
      - threadpoolctl==3.2.0
      - tifffile==2023.8.30
      - tinycss2==1.2.1
      - toml==0.10.2
      - tomli==2.0.1
      - toolz==0.12.0
      - tornado==6.3.3
      - tqdm==4.66.1
      - traitlets==5.9.0
      - typeguard==2.13.3
      - typing-extensions==4.5.0
      - tzdata==2023.3
      - tzlocal==5.2
      - uncertainties==3.1.7
      - uri-template==1.3.0
      - urllib3==1.26.18
      - validators==0.22.0
      - vit-keras==0.1.2
      - wandb==0.17.3
