
# picasso:
#   spot_size: 15
#   localised_frame: 100

train_size: 0.8
val_size: 0.1
test_size: 0.1

images:
  picasso_box: 31
  xy_res: 110
  magnification: 111.11
  ill_NA: 1.4
  det_NA: 1.3
  n: 1.335
  ill_wavelength: 635
  det_wavelength: 635
  train:
    # in nm
    z_step: 20
    shape: [41, 512, 512]

  exp:
    shape: [64, 64]

random_seed: 42

DEBUG: false

# in nm above and below focal point
z_range: 1000
