
picasso:
  spot_size: 31
  localised_frame: 20

train_size: 0.8
val_size: 0.1
test_size: 0.1

images:
  train:
    # in nm
    z_step: 50
    xy_res: 100
    shape: [41, 512, 512]
  exp:
    shape: [64, 64]

random_seed: 42

DEBUG: false

# in nm above and below focal point
z_range: 1000
